---
layout:     post
title:      "python异常处理"
subtitle:   
date:       2023-08-06
author:     胖胖很瘦
thumbnail:  /images/f343c694/thumbnail.png
catalog: true
categories: python
original_url: https://mp.weixin.qq.com/s/HbqPdCGTDh24hqwFBX5ROA
tags:
    - python
    - py小白
---

点击上方蓝字关注我们

![](/images/f343c694/1.png)

**哈哈哈**

        作为一个码农, 每天都在写代码, 不可避免的会出现错误, 也有一些时候, 知道可能会出现错误, 必须要在代码中处理, 以免影响代码正常流程, 这篇讲一下常见的异常错误, 以及如何处理异常

**常见异常**

* AssertError: 断言语句（assert）失败
* AttributeError: 尝试访问未知的对象属性
* EOFError: 用户输入文件末尾标志EOF（Ctrl+d）
* FloatingPointError: 浮点计算错误
* GeneratorExit: generator.close()方法被调用的时候
* ImportError: 导入模块失败的时候
* IndexError: 索引超出序列的范围
* KeyError: 字典中查找一个不存在的关键字
* KeyboardInterrupt: 用户输入中断键（Ctrl+c）
* MemoryError: 内存溢出（可通过删除对象释放内存）
* NameError: 尝试访问一个不存在的变量
* NotImplementedError: 尚未实现的方法
* OSError: 操作系统产生的异常（例如打开一个不存在的文件）
* OverflowError: 数值运算超出最大限制
* ReferenceError: 弱引用（weak reference）试图访问一个已经被垃圾回收机制回收了的对象
* RuntimeError: 一般运行时的错误
* StopIteration: 迭代器没有更多的值
* SyntaxError: 语法错误
* IndentationError: 缩进错误
* TabError: Tab和空格混合使用
* SystemError: Python编译器系统错误
* SystemExit: Python编译器进程被关闭
* TypeError: 不同类型间的无效操作
* UnboundLocalError: 访问一个未初始化的本地变量（NameError的子类）
* UnicodeError: Unicode相关的错误（ValueError的子类）
* UnicodeEncodeError: Unicode编码时的错误（UnicodeError的子类）
* UnicodeDecodeError: Unicode解码时的错误（UnicodeError的子类）
* UnicodeTranslateError: Unicode转换时的错误（UnicodeError的子类）
* ValueError: 传入无效的参数
* ZeroDivisionError: 除数为零

**异常处理**

格式: 

```
try:  
    # 代码块, 没有异常正常完成  
  
except 异常类型1:  
    # try代码块捕捉到异常类型1, 自定义处理后续流程  
  
except 异常类型2 as e2：  
    # try代码块捕捉到异常类型1, 自定义处理后续流程  
    # 将异常赋值给e2  
  
except (异常类型3, 异常类型4...)  
    # try代码块捕捉到异常类型3或4, 自定义处理后续流程  
  
excpet Exception:  
    # 尝试捕捉任何错误, 自定义处理后续流程  
  
else:  
    # try代码块中, 如果没有出现任何异常，将会执行此处代码  
  
finally:  
    # 任何情况都会执行的代码块, 无论有没有报错
```

多说无用, 写个小例子

```
# -*- coding: utf-8 -*-  
# @Author: Mehaei  
# @Date: 2023-08-06 21:01:36  
# @Last Modified by: Mehaei  
# @Last Modified time: 2023-08-06 21:36:51  
  
# 自定义的异常类  
class UnknownError(Exception):  
    pass  
  
  
# 小例子  
try:  
    raise UnknownError  
    print(1/0)  
except ZeroDivisionError:  
    print("除数为0, 请检查代码")  
except UnknownError:  
    print("自定义的异常, 不知道什么错误")  
# 使用as语句, 将错误赋值给变量e  
except Exception as e:  
    print(f"不知道什么错误: {e}")  
else:  
    print("代码块没有异常")  
finally:  
    print("不管有没有异常, 我都会执行")
```

输出:

```
自定义的异常, 不知道什么错误  
不管有没有异常, 我都会执行  
[Finished in 0.1s]
```

**这篇完了**

        代码异常处理还有个典型的应用就是给代码块加个装饰器, 用来重试代码块或函数, 下篇讲装饰器

壹伴精选

围观

![](/images/f343c694/2.png)[python类的魔术方法](http://mp.weixin.qq.com/s?__biz=MzUyMzk3OTYyMQ==&mid=2247487222&idx=1&sn=fd2349cb8902e40f41f7568d3ccefedd&chksm=fa3510fccd4299eadd597f56ef5912c334b79642eddb88fe7b5e9cf0b3e7655d9590a2234e18&scene=21#wechat_redirect)

丨更多

热文

[python中的类和对象](http://mp.weixin.qq.com/s?__biz=MzUyMzk3OTYyMQ==&mid=2247487198&idx=1&sn=2c6d08f9e064cab5b6b7dc4ca2da0ca4&chksm=fa3510d4cd4299c219b8a9ab2c3f3a4c7b9c4a75186fffdfc07b605923b764883226e61aea88&scene=21#wechat_redirect)

丨更多

热文

[python常用模块和方法](http://mp.weixin.qq.com/s?__biz=MzUyMzk3OTYyMQ==&mid=2247487170&idx=1&sn=0685999717389304ddb0d641a3e1dba7&chksm=fa3510c8cd4299de5d79549f6afd150751dde050934506249a20161a5d0769f901874d494884&scene=21#wechat_redirect)

丨更多

热文

[python常用内置函数](http://mp.weixin.qq.com/s?__biz=MzUyMzk3OTYyMQ==&mid=2247487046&idx=1&sn=84f9503574d251a5f888a6341b13d6de&chksm=fa35104ccd42995a97f93b7c38671897d01b1ba298eb5ea5bd2e1d8f2d089d4d12e416692065&scene=21#wechat_redirect)

丨更多

热文

[python内部函数和闭包](http://mp.weixin.qq.com/s?__biz=MzUyMzk3OTYyMQ==&mid=2247487031&idx=1&sn=9a648d2b62c6d35a0d841289bc8a2e7f&chksm=fa35103dcd42992b4906229b88e9f2848bd40f7faeb31bfc2ffdb09c5f7d40014e02109feb8d&scene=21#wechat_redirect)

丨更多

![](/images/f343c694/3.png)